version: "3.5"

services:
  postgres:
    image: docker.io/library/postgres:12
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-24889}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-odyseja}"
      POSTGRES_USER: "${POSTGRES_USER:-odyseja}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-odyseja}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

volumes:
  postgres-storage:

networks:
  default:
