version: '3.8'
services:
  postgres:
    image: docker.io/library/postgres:12
    container_name: postgres-odyseja-dev
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-odyseja}"
      POSTGRES_USER: "${POSTGRES_USER:-odyseja}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-odyseja}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: odyseja-backend:latest
    container_name: backend-dev
    restart: always
    network_mode: host
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/odyseja
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-odyseja}"
      SPRING_DATASOURCE_USSERNAME: odyseja
      SERVER_PORT: 8082
      GOOGLE_APPLICATION_CREDENTIALS: /root/odysejapka/creds.json
      SPRING_CONFIG_IMPORT: file:/properties.yml
      TEXAPI_API_KEY: "${TEXAPI_API_KEY:-}"
    volumes:
      - /root/odysejapka/creds.json:/root/odysejapka/creds.json:ro
      - ./properties.yml:/properties.yml:ro

  frontend:
    image: odyseja-ui:latest
    container_name: frontend-dev
    restart: always
    ports:
      - "3000:4173"
    depends_on:
      - backend
    environment:
      PUBLIC_BASE_URL: "${BACKEND_URL:-http://localhost:8082}"
      PUBLIC_FRONTEND_URL: "${FRONTEND_URL:-http://localhost:3000}"

  forms-ui:
    image: odyseja-forms-ui:latest
    container_name: forms-ui-dev
    restart: always
    network_mode: host
    depends_on:
      - backend
    environment:
      PORT: 3001
      HOST: 0.0.0.0
      ORIGIN: "https://panel.odyseja.org"
      BACKEND_URL: "http://localhost:8082"
      AUTH_SECRET: "${AUTH_SECRET}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
      AUTH0_ISSUER: "${AUTH0_ISSUER:-https://odyseja.eu.auth0.com}"
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE:-https://odyseja.eu.auth0.com/api/v2/}"

volumes:
  postgres-data:
