version: '3.8'
services:
  postgres:
    image: docker.io/library/postgres:12
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-odyseja}"
      POSTGRES_USER: "${POSTGRES_USER:-odyseja}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-odyseja}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: 1grzyb1/odyseja:latest
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/odyseja
      SPRING_DATASOURCE_PASSWORD: odyseja
      SPRING_DATASOURCE_USSERNAME: odyseja

  frontend:
    image: 1grzyb1/odyseja-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://backend:8081

volumes:
  postgres-data:
