version: '3.8'
services:
  postgres:
    image: docker.io/library/postgres:12
    container_name: postgres-odyseja-dev
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-odyseja}"
      POSTGRES_USER: "${POSTGRES_USER:-odyseja}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-odyseja}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: 1grzyb1/odyseja:latest
    container_name: backend-dev
    restart: always
    pull_policy: always
    network_mode: host
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/odyseja
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-odyseja}"
      SPRING_DATASOURCE_USSERNAME: odyseja
      SERVER_PORT: 8082
      GOOGLE_APPLICATION_CREDENTIALS: /root/odysejapka/creds.json

  frontend:
    image: 1grzyb1/odyseja-frontend:latest
    container_name: frontend-dev
    restart: always
    pull_policy: always
    ports:
      - "3000:4173"
    depends_on:
      - backend
    environment:
      PUBLIC_BASE_URL: "${BACKEND_URL:-http://localhost:8082}"
      PUBLIC_CALLBACK_URL: "${CALLBACK_URL:-http://localhost:3000/callback}"

volumes:
  postgres-data:
