CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON performance

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();

CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON age

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();

CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON city

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();

CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON info

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();

CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON problem

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();

CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON sponsor

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();

CREATE TRIGGER t BEFORE INSERT OR UPDATE OR DELETE ON stage

    FOR EACH ROW EXECUTE PROCEDURE change_trigger();